config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :api do
    get 'vue/data', to: 'vue#pass_data_to_vue'

  end

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

    namespace :admin do

      root 'admins#index'

    end


    root to: 'landing#index'

    # Users
    resources :users
    resources :sessions, only: [:create, :destroy]
    get 'enter', to: 'users#enter', as: 'enter'
    get 'logout', to: 'sessions#destroy', as: 'logout'

    get 'sessions/new'
    get 'sessions/create'
    get 'sessions/destroy'

  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true
end

app/controllers/admin/admins_controller.rb
class Admin::AdminsController < ApplicationController

  layout 'admin/application'
  helper_method :admin?

  def index
    @users = User.all

    if admin?
      render 'admin/index'
    else
      redirect_to '/'
    end

  end


  private

  def admin?
    current_user && current_user.role == 1
  end

end

app/controllers/api/vue_controller.rb
module Api
class VueController < ApplicationController

  def pass_data_to_vue

    @pass_data_to_vue = 'Data via Api Controller!'
    render json: { pass_data_to_vue: @pass_data_to_vue }

  end

end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale
  helper_method :current_user, :set_user, :authenticated?, :is_this_user?
  def set_locale
    I18n.locale = params[:locale] || session[:locale] || I18n.default_locale
    session[:locale] = I18n.locale
  end

  def default_url_options(options = {})
    { locale: I18n.locale }
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end

  def admin?
    current_user.role == 1
  end

  def set_user
    @user = User.find(params[:id])
  end

  def authenticated?
    redirect_to root_url unless current_user || @user
  end

  def is_this_user?
    redirect_to root_url if current_user.id != @user.id
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController

  def index

    @prop_to_vue = 'Variable from Rails View'
    render 'landing/index'

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by_email(params[:email])
    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      user.role == 1 ? redirect_to(admin_root_path, notice: 'Is Admin') : redirect_to(user , notice: 'Not Admin')
    else
      flash.now[:alert] = I18n.t 'email_or_password_wrong'
      render 'users/login_register'
    end
  end
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show update destroy]
  before_action :authenticated?, except: %i[enter create]
  before_action :is_this_user?, except: %i[enter create]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  def enter


    @user = User.new
    @user.save

    if current_user
      redirect_to(current_user)
    else
      render('users/login_register')


    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.save
    session[:user_id] = @user.id
    redirect_to @user, notice: I18n.t('user_registered')
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @user.update_attributes(user_params)
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_root_path, notice: 'User was successfully destroyed.' }
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :role)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<div class="flex flex-col md:flex-row">


  <%= render 'layouts/admin/sidebar' %>


  <div class="main-content flex-1 bg-gray-100 mt-12 mt-12 md:mt-2 py-8">
    <% unless notice.nil? %>
      <div class="bg-teal-100 border-t-4 border-teal-500 rounded-b text-teal-900 px-4 py-3 shadow-md mb-5" role="alert">
        <div class="flex">
          <div class="py-1"><svg class="fill-current h-6 w-6 text-teal-500 mr-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M2.93 17.07A10 10 0 1 1 17.07 2.93 10 10 0 0 1 2.93 17.07zm12.73-1.41A8 8 0 1 0 4.34 4.34a8 8 0 0 0 11.32 11.32zM9 11V9h2v6H9v-4zm0-6h2v2H9V5z"/></svg></div>
          <div>
            <p class="font-bold"><%= notice %></p>
          </div>
        </div>
      </div>
    <% end %>
    <div class="bg-custom p-2 shadow text-xl text-white">
      <h3 class="font-bold pl-2">Analytics</h3>
    </div>

    <div class="flex flex-wrap">
      <div class="w-full md:w-1/2 xl:w-1/3 p-3">
        <!--Metric Card-->
        <div class="bg-green-100 border-b-4 border-green-600 rounded-lg shadow-lg p-5">
          <div class="flex flex-row items-center">
            <div class="flex-shrink pr-4">
              <div class="rounded-full p-5 bg-green-600"><i class="fa fa-wallet fa-2x fa-inverse"></i></div>
            </div>
            <div class="flex-1 text-right md:text-center">
              <h5 class="font-bold uppercase text-gray-600">Total Revenue</h5>
              <h3 class="font-bold text-3xl">$3249 <span class="text-green-500"><i class="fas fa-caret-up"></i></span></h3>
            </div>
          </div>
        </div>
        <!--/Metric Card-->
      </div>
      <div class="w-full md:w-1/2 xl:w-1/3 p-3">
        <!--Metric Card-->
        <div class="bg-orange-100 border-b-4 border-orange-500 rounded-lg shadow-lg p-5">
          <div class="flex flex-row items-center">
            <div class="flex-shrink pr-4">
              <div class="rounded-full p-5 bg-orange-600"><i class="fas fa-users fa-2x fa-inverse"></i></div>
            </div>
            <div class="flex-1 text-right md:text-center">
              <h5 class="font-bold uppercase text-gray-600">Total Users</h5>
              <h3 class="font-bold text-3xl">249 <span class="text-orange-500"><i class="fas fa-exchange-alt"></i></span></h3>
            </div>
          </div>
        </div>
        <!--/Metric Card-->
      </div>
      <div class="w-full md:w-1/2 xl:w-1/3 p-3">
        <!--Metric Card-->
        <div class="bg-yellow-100 border-b-4 border-yellow-600 rounded-lg shadow-lg p-5">
          <div class="flex flex-row items-center">
            <div class="flex-shrink pr-4">
              <div class="rounded-full p-5 bg-yellow-600"><i class="fas fa-user-plus fa-2x fa-inverse"></i></div>
            </div>
            <div class="flex-1 text-right md:text-center">
              <h5 class="font-bold uppercase text-gray-600">New Users</h5>
              <h3 class="font-bold text-3xl">2 <span class="text-yellow-600"><i class="fas fa-caret-up"></i></span></h3>
            </div>
          </div>
        </div>
        <!--/Metric Card-->
      </div>
      <div class="w-full md:w-1/2 xl:w-1/3 p-3">
        <!--Metric Card-->
        <div class="bg-blue-100 border-b-4 border-blue-500 rounded-lg shadow-lg p-5">
          <div class="flex flex-row items-center">
            <div class="flex-shrink pr-4">
              <div class="rounded-full p-5 bg-blue-600"><i class="fas fa-server fa-2x fa-inverse"></i></div>
            </div>
            <div class="flex-1 text-right md:text-center">
              <h5 class="font-bold uppercase text-gray-600">Server Uptime</h5>
              <h3 class="font-bold text-3xl">152 days</h3>
            </div>
          </div>
        </div>
        <!--/Metric Card-->
      </div>
      <div class="w-full md:w-1/2 xl:w-1/3 p-3">
        <!--Metric Card-->
        <div class="bg-indigo-100 border-b-4 border-indigo-500 rounded-lg shadow-lg p-5">
          <div class="flex flex-row items-center">
            <div class="flex-shrink pr-4">
              <div class="rounded-full p-5 bg-indigo-600"><i class="fas fa-tasks fa-2x fa-inverse"></i></div>
            </div>
            <div class="flex-1 text-right md:text-center">
              <h5 class="font-bold uppercase text-gray-600">To Do List</h5>
              <h3 class="font-bold text-3xl">7 tasks</h3>
            </div>
          </div>
        </div>
        <!--/Metric Card-->
      </div>
      <div class="w-full md:w-1/2 xl:w-1/3 p-3">
        <!--Metric Card-->
        <div class="bg-red-100 border-b-4 border-red-500 rounded-lg shadow-lg p-5">
          <div class="flex flex-row items-center">
            <div class="flex-shrink pr-4">
              <div class="rounded-full p-5 bg-red-600"><i class="fas fa-inbox fa-2x fa-inverse"></i></div>
            </div>
            <div class="flex-1 text-right md:text-center">
              <h5 class="font-bold uppercase text-gray-600">Issues</h5>
              <h3 class="font-bold text-3xl">3 <span class="text-red-500"><i class="fas fa-caret-up"></i></span></h3>
            </div>
          </div>
        </div>
        <!--/Metric Card-->
      </div>
    </div>


    <div class="flex flex-row flex-wrap flex-grow mt-2">

      <div class="w-full md:w-1/2 xl:w-1/3 p-3">
        <!--Graph Card-->
        <div class="bg-white border-transparent rounded-lg shadow-lg">
          <div class="bg-gray-400 uppercase text-gray-800 border-b-2 border-gray-500 rounded-tl-lg rounded-tr-lg p-2">
            <h5 class="font-bold uppercase text-gray-600">Users</h5>
          </div>
          <div class="p-5">
            <% @current_user.role %>
            <% @users.each do |user| %>
              <tr>
                <td><%= user.email %></td>
                <td><%= link_to 'Show', user %></td>
                <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </div>
        </div>
        <!--/Graph Card-->
      </div>





      <div class="w-full md:w-1/2 xl:w-1/3 p-3">
        <!--Table Card-->
        <div class="bg-white border-transparent rounded-lg shadow-lg">
          <div class="bg-gray-400 border-b-2 border-gray-500 rounded-tl-lg rounded-tr-lg p-2">
            <h5 class="font-bold uppercase text-gray-600">Table</h5>
          </div>
          <div class="p-5">
            <table class="w-full p-5 text-gray-700">
              <thead>
              <tr>
                <th class="text-left text-blue-900">Name</th>
                <th class="text-left text-blue-900">Side</th>
                <th class="text-left text-blue-900">Role</th>
              </tr>
              </thead>

              <tbody>
              <tr>
                <td>Obi Wan Kenobi</td>
                <td>Light</td>
                <td>Jedi</td>
              </tr>
              <tr>
                <td>Greedo</td>
                <td>South</td>
                <td>Scumbag</td>
              </tr>
              <tr>
                <td>Darth Vader</td>
                <td>Dark</td>
                <td>Sith</td>
              </tr>
              </tbody>
            </table>

            <p class="py-2"><a href="#">See More issues...</a></p>

          </div>
        </div>
        <!--/table Card-->
      </div>

      <div class="w-full md:w-1/2 xl:w-1/3 p-3">
        <!--Template Card-->
        <div class="bg-white border-transparent rounded-lg shadow-lg">
          <div class="bg-gray-400 border-b-2 border-gray-500 rounded-tl-lg rounded-tr-lg p-2">
            <h5 class="font-bold uppercase text-gray-600">Template</h5>
          </div>
          <div class="p-5">

          </div>
        </div>
        <!--/Template Card-->
      </div>


    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="relative bg-indigo-800 border-b-2 border-gray-300 text-gray-900">
  <div class="container mx-auto flex justify-between">
    <div class="relative block p-4 lg:p-6 text-lg text-blue-600 font-bold">
      <%= link_to root_path do %>
        <%= image_pack_tag 'rails_vuejs_tailwindcss.png', width: "220", alt: "Logo" %>
      <% end %>
    </div>
    <ul class="flex">
      <!--Regular Link-->
      <li class="text-gray-400 hover:bg-custom hover:text-white">
        <a href="#" class="relative block py-6 px-2 lg:p-6 text-sm text-lg font-bold">Normal</a>
      </li>

      <li class="hoverable text-custom hover:bg-custom hover:text-white">
        <a href="#" class="relative block py-6 px-4 lg:p-6 text-lg font-bold hover:bg-custom hover:text-white"><i class="fas fa-infinity"></i> <%= t(:text) %></a>
        <div class="p-6 mega-menu mb-16 sm:mb-0 shadow-xl bg-custom">
          <div class="container mx-auto w-full flex flex-wrap justify-between mx-2">
            <div class="w-full text-white mb-8">
              <h2 class="font-bold text-2xl">Main Hero Message for the menu section</h2>
              <p>Sub-hero message, not too long and not too short. Make it just right!</p>
            </div>
            <ul class="px-4 w-full sm:w-1/2 lg:w-1/4 border-gray-600 border-b sm:border-r lg:border-b-0 pb-6 pt-6 lg:pt-3">
              <div class="flex items-center">
                <svg class="h-8 mb-3 mr-3 fill-current text-white" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                  <path d="M3 6c0-1.1.9-2 2-2h8l4-4h2v16h-2l-4-4H5a2 2 0 0 1-2-2H1V6h2zm8 9v5H8l-1.67-5H5v-2h8v2h-2z"></path>
                </svg>
                <h3 class="font-bold text-lg text-white text-bold mb-2">Heading 1</h3>
              </div>
              <p class="text-gray-100 text-sm">Quarterly sales are at an all-time low create spaces to explore the accountable talk and blind vampires.</p>
              <div class="flex items-center py-3">
                <svg class="h-6 pr-3 fill-current text-blue-300" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                  <path d="M20 10a10 10 0 1 1-20 0 10 10 0 0 1 20 0zm-2 0a8 8 0 1 0-16 0 8 8 0 0 0 16 0zm-8 2H5V8h5V5l5 5-5 5v-3z"></path>
                </svg>
                <a href="#" class="text-white bold border-b-2 border-blue-300 hover:text-blue-300">Find out more...</a>
              </div>
            </ul>
            <ul class="px-4 w-full sm:w-1/2 lg:w-1/4 border-gray-600 border-b sm:border-r-0 lg:border-r lg:border-b-0 pb-6 pt-6 lg:pt-3">
              <div class="flex items-center">
                <svg class="h-8 mb-3 mr-3 fill-current text-white" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                  <path d="M4.13 12H4a2 2 0 1 0 1.8 1.11L7.86 10a2.03 2.03 0 0 0 .65-.07l1.55 1.55a2 2 0 1 0 3.72-.37L15.87 8H16a2 2 0 1 0-1.8-1.11L12.14 10a2.03 2.03 0 0 0-.65.07L9.93 8.52a2 2 0 1 0-3.72.37L4.13 12zM0 4c0-1.1.9-2 2-2h16a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4z"></path>
                </svg>
                <h3 class="font-bold text-lg text-white text-bold mb-2">Heading 2</h3>
              </div>
              <p class="text-gray-100 text-sm">Prioritize these line items game-plan draw a line in the sand come up with something buzzworthy UX upstream selling.</p>
              <div class="flex items-center py-3">
                <svg class="h-6 pr-3 fill-current text-blue-300" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                  <path d="M20 10a10 10 0 1 1-20 0 10 10 0 0 1 20 0zm-2 0a8 8 0 1 0-16 0 8 8 0 0 0 16 0zm-8 2H5V8h5V5l5 5-5 5v-3z"></path>
                </svg>
                <a href="#" class="text-white bold border-b-2 border-blue-300 hover:text-blue-300">Find out more...</a>
              </div>
            </ul>
            <ul class="px-4 w-full sm:w-1/2 lg:w-1/4 border-gray-600 border-b sm:border-b-0 sm:border-r md:border-b-0 pb-6 pt-6 lg:pt-3">
              <div class="flex items-center">
                <svg class="h-8 mb-3 mr-3 fill-current text-white" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                  <path d="M2 4v14h14v-6l2-2v10H0V2h10L8 4H2zm10.3-.3l4 4L8 16H4v-4l8.3-8.3zm1.4-1.4L16 0l4 4-2.3 2.3-4-4z"></path>
                </svg>
                <h3 class="font-bold text-lg text-white text-bold mb-2">Heading 3</h3>
              </div>
              <p class="text-gray-100 text-sm">This proposal is a win-win situation which will cause a stellar paradigm shift, let's touch base off-line before we fire the new ux experience.</p>
              <div class="flex items-center py-3">
                <svg class="h-6 pr-3 fill-current text-blue-300" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                  <path d="M20 10a10 10 0 1 1-20 0 10 10 0 0 1 20 0zm-2 0a8 8 0 1 0-16 0 8 8 0 0 0 16 0zm-8 2H5V8h5V5l5 5-5 5v-3z"></path>
                </svg>
                <a href="#" class="text-white bold border-b-2 border-blue-300 hover:text-blue-300">Find out more...</a>
              </div>
            </ul>
            <ul class="px-4 w-full sm:w-1/2 lg:w-1/4 border-gray-600 pb-6 pt-6 lg:pt-3">
              <div class="flex items-center">
                <svg class="h-8 mb-3 mr-3 fill-current text-white" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                  <path d="M9 12H1v6a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-6h-8v2H9v-2zm0-1H0V5c0-1.1.9-2 2-2h4V2a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v1h4a2 2 0 0 1 2 2v6h-9V9H9v2zm3-8V2H8v1h4z"></path>
                </svg>
                <h3 class="font-bold text-lg text-white text-bold mb-2">Heading 4</h3>
              </div>
              <p class="text-gray-100 text-sm">This is a no-brainer to wash your face, or we need to future-proof this high performance keywords granularity.</p>
              <div class="flex items-center py-3">
                <svg class="h-6 pr-3 fill-current text-blue-300" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                  <path d="M20 10a10 10 0 1 1-20 0 10 10 0 0 1 20 0zm-2 0a8 8 0 1 0-16 0 8 8 0 0 0 16 0zm-8 2H5V8h5V5l5 5-5 5v-3z"></path>
                </svg>
                <a href="#" class="text-white bold border-b-2 border-blue-300 hover:text-blue-300">Find out more...</a>
              </div>
            </ul>
          </div>
        </div>
      </li>
      <li class="<% if current_user %>hoverable <% end %>text-gray-400 hover:bg-custom hover:text-white">
        <% if current_user %>
          <a href="#" class="relative block py-6 px-4 lg:p-6 text-sm text-lg font-bold hover:bg-custom hover:text-white">
            <i class="fas fa-user"></i>
            <%= current_user.email %></a>
          <div class="mega-menu absolute max-w-xs mb-16 sm:mb-0 shadow-xl bg-custom" style="left: auto;width: 203px;">

            <ul class="list-reset">
              <% if current_user.role == 1 %>
                <li><%= link_to t(:control_panel), admin_root_path, class: "relative block py-6 px-2 lg:p-6 text-sm text-lg font-bold" %></li>
              <% else %>
                <li><%= link_to t(:cabinet), user_path(id: current_user.id), class: "relative block py-6 px-2 lg:p-6 text-sm text-lg font-bold" %></li>
              <% end %>
              <li><%= link_to t(:exit), logout_path, class: "relative block py-6 px-2 lg:p-6 text-sm text-lg font-bold" %></li>
            </ul>
          </div>
        <% else %>
          <%= link_to 'enter', class: "relative block py-6 px-2 lg:p-6 text-sm text-lg font-bold" do %>
            <i class="fas fa-door-open"></i>
            <%= t(:enter) %>
          <% end %>
        <% end %>


      </li>
      <li class="hoverable text-gray-400 hover:bg-custom hover:text-white">

        <a href="#" class="relative block py-6 px-4 lg:p-6 text-sm text-lg font-bold hover:bg-custom hover:text-white">
          <i class="fas fa-language"></i>
          <%= t(:language) %></a>
        <div class="mega-menu absolute max-w-xs mb-16 sm:mb-0 shadow-xl bg-custom" style="left: auto;width: 136px;">

          <ul class="list-reset">
            <li><%= link_to "Русский", {locale: :ru}, class: "relative block py-6 px-2 lg:p-6 text-sm text-lg font-bold" %></li>
            <li><%= link_to "English", {locale: :en}, class: "relative block py-6 px-2 lg:p-6 text-sm text-lg font-bold" %></li>
          </ul>
        </div>

      </li>
    </ul>
  </div>
</nav>

app/views/layouts/admin/_nav.html.erb
<!--Nav-->
<nav class="bg-black pt-2 md:pt-1 pb-1 px-1 mt-0 h-auto fixed w-full z-20 top-0">

  <div class="flex flex-wrap items-center">
    <div class="flex flex-shrink md:w-1/3 justify-center md:justify-start text-white">
      <%= link_to root_path do %>
        <%= image_pack_tag 'rails_vuejs_tailwindcss.png', width: "220", alt: "Logo" %>
      <% end %>
    </div>

    <div class="flex flex-1 md:w-1/3 justify-center md:justify-start text-white px-2">
                <span class="relative w-full">
                    <input type="search" placeholder="Search" class="w-full bg-gray-800 text-sm text-white transition border border-transparent focus:outline-none focus:border-gray-700 rounded py-1 px-2 pl-10 appearance-none leading-normal">
                    <div class="absolute search-icon" style="top: .5rem; left: .8rem;">
                        <svg class="fill-current pointer-events-none text-white w-4 h-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                            <path d="M12.9 14.32a8 8 0 1 1 1.41-1.41l5.35 5.33-1.42 1.42-5.33-5.34zM8 14A6 6 0 1 0 8 2a6 6 0 0 0 0 12z"></path>
                        </svg>
                    </div>
                </span>
    </div>

    <div class="flex w-full pt-2 content-center justify-between md:w-1/3 md:justify-end">
      <ul class="list-reset flex justify-between flex-1 md:flex-none items-center">

        <li class="hoverable text-gray-400 hover:bg-custom hover:text-white">

          <a href="#" class="relative block py-6 px-4 lg:p-6 text-sm text-lg font-bold hover:bg-custom hover:text-white">
            <i class="fas fa-language"></i>
            <%= t(:language) %></a>
          <div class="mega-menu absolute max-w-xs mb-16 sm:mb-0 shadow-xl bg-custom" style="left: auto;width: 136px;">

            <ul class="list-reset">
              <li><%= link_to "Русский", {locale: :ru}, class: "relative block py-6 px-2 lg:p-6 text-sm text-lg font-bold" %></li>
              <li><%= link_to "Українська", {locale: :ua}, class: "relative block py-6 px-2 lg:p-6 text-sm text-lg font-bold" %></li>
            </ul>
          </div>

        </li>
        <li class="<% if current_user %>hoverable <% end %>text-gray-400 hover:bg-custom hover:text-white">
          <% if current_user %>
            <a href="#" class="relative block py-6 px-4 lg:p-6 text-sm text-lg font-bold hover:bg-custom hover:text-white">
              <i class="fas fa-user"></i>
              <%= current_user.email %></a>
            <div class="mega-menu absolute max-w-xs mb-16 sm:mb-0 shadow-xl bg-custom" style="left: auto;width: 203px;">

              <ul class="list-reset">
                <li><%= link_to t(:exit), logout_path, class: "relative block py-6 px-2 lg:p-6 text-sm text-lg font-bold" %></li>
              </ul>
            </div>
          <% else %>
            <%= link_to 'enter', class: "relative block py-6 px-2 lg:p-6 text-sm text-lg font-bold" do %>
              <i class="fas fa-door-open"></i>
              <%= t(:enter) %>
            <% end %>
          <% end %>

        </li>
      </ul>
    </div>
  </div>

</nav>

app/views/users/_login_form.html.erb
<!-- Login -->
<div class="w-full md:w-1/2 px-3 pr-8">
  <%= form_tag sessions_path do %>
    <h1 class="font-hairline text-5xl mb-6 text-center"><%= t(:enter_cabinet) %></h1>
    <div class="border-custom p-8 border-t-8 bg-white mb-6 rounded-lg shadow-lg">
      <% unless alert.nil? %>
        <div class="mb-2 bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
          <strong class="font-bold"><%= t(:attention) %>!</strong>
          <span class="block sm:inline" id="alert"><%= alert %>.</span>
          <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
  </span>
        </div>
      <% end %>

      <div class="mb-4">

        <%= label_tag 'E-mail', nil, :class => "font-bold text-grey-darker block mb-2" %>
        <%= text_field_tag :email, nil, :class => "block appearance-none w-full bg-white border border-grey-light hover:border-grey px-2 py-2 rounded shadow" %>
      </div>

      <div class="mb-4">
        <%= label_tag t(:password), nil, :class => "font-bold text-grey-darker block mb-2" %>
        <%= password_field_tag :password, nil, autocomplete: "current-password", class: "block appearance-none w-full bg-white border border-grey-light hover:border-grey px-2 py-2 rounded shadow" %>
      </div>

      <div class="flex items-stretch items-center">
        <div class="flex-1 text-center px-4 py-2 m-2">
          <%= submit_tag t(:enter), class: "bg-custom hover:bg-black text-white hover:text-custom font-bold py-2 px-4 rounded" %>




        </div>



      </div>

    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
  <tr>
    <th>Email</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.email %></td>
      <td><%= link_to 'Show', user %></td>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>